defaults:

  logdir: null
  traindir: null
  evaldir: null
  offline_traindir: ''
  offline_evaldir: ''
  seed: 0
  deterministic_run: False
  steps: 1e3
  parallel: True
  eval_mode: False
  eval_every: 1e4
  eval_episode_num: 1
  log_every: 1e2
  reset_every: 0
  device: 'cuda'
  compile: True
  precision: 32
  debug: False
  save_model: True
  video_pred_log: True

  # Environment
  task: 'dmc_walker_walk'
  size: [64, 64]
  envs: 1
  action_repeat: 2
  time_limit: 5002
  grayscale: False
  prefill: 2500
  reward_EMA: True

  # Model
  dyn_hidden: 32
  dyn_deter: 32
  dyn_stoch: 32
  dyn_discrete: 32
  dyn_rec_depth: 1
  dyn_mean_act: 'none'
  dyn_std_act: 'sigmoid2'
  dyn_min_std: 0.1
  grad_heads: ['decoder', 'reward', 'cont']
  units: 32
  act: 'SiLU'
  norm: True
  encoder:
    {mlp_keys: 'image', cnn_keys: 'x', act: 'SiLU', norm: True, cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 2, mlp_units: 32, symlog_inputs: True}
  decoder:
    {mlp_keys: 'image', cnn_keys: 'x', act: 'SiLU', norm: True, cnn_depth: 32, kernel_size: 4, minres: 4, mlp_layers: 2, mlp_units: 32, cnn_sigmoid: False, image_dist: mse, vector_dist: symlog_mse, outscale: 1.0}
  actor:
    {layers: 3, dist: 'normal', mlp_units: 32, entropy: 3e-4, unimix_ratio: 0.01, std: 'learned', min_std: 0.1, max_std: 1.0, temp: 0.1, lr: 3e-5, eps: 1e-5, grad_clip: 100.0, outscale: 1.0}
  critic:
    {layers: 2, dist: 'symlog_disc',mlp_units: 32, slow_target: True, slow_target_update: 1, slow_target_fraction: 0.02, lr: 3e-4, eps: 3e-5, grad_clip: 100.0, outscale: 0.0}
  reward_head:
    {layers: 2, dist: 'symlog_disc',mlp_units: 32, loss_scale: 1.0, outscale: 0.0}
  cont_head:
    {layers: 2, loss_scale: 1.0,mlp_units: 32, outscale: 1.0}
  risk_head:
    {layers: 2, loss_scale: 1.0,mlp_units: 32, outscale: 1.0}
  dyn_scale: 0.5
  rep_scale: 0.1
  kl_free: 1.0
  weight_decay: 0.0
  unimix_ratio: 0.01
  initial: 'learned'

  # Training
  batch_size: 128
  batch_length: 32
  train_ratio: 512
  pretrain: 100
  model_lr: 3e-4
  opt_eps: 1e-6
  grad_clip: 500
  dataset_size: 10000
  opt: 'adam'

  # Behavior.
  discount: 0.997
  discount_lambda: 0.95
  imag_horizon: 10
  imag_gradient: 'dynamics'
  imag_gradient_mix: 0.0
  eval_state_mean: False
  num_samples: 5

  # Exploration
  expl_behavior: 'greedy'
  # expl_behavior: 'plan2explore'
  expl_until: 0.0
  expl_extr_scale: 0.0
  expl_intr_scale: 1.0
  disag_target: 'stoch'
  disag_log: True
  disag_models: 10
  disag_offset: 1
  disag_layers: 4
  disag_units: 400
  disag_action_cond: False


dmc_vision:
  steps: 1e8
  action_repeat: 1
  pretrain: 10
  prefill: 195
  envs: 1
  train_ratio: 512
  video_pred_log: True


debug:
  debug: True
  pretrain: 10
  prefill: 10
  dataset_size: 10
  batch_size: 20
  batch_length: 20
